/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import {useFrame} from "@react-three/fiber";
import {SUN_SIZE} from "./Sun";

export const EARTH_SIZE = SUN_SIZE / 109;

export default function Earth(props) {
    const group = useRef()
    const {nodes, materials} = useGLTF('/models/Earth.glb');

    useFrame(() => {
        group.current.rotation.y += 0.001;
    })

    return (
        <mesh ref={props.earthRef} rotation={[0,0,0.418879]}>
            <group scale={EARTH_SIZE} ref={group} {...props} dispose={null}>
                <mesh geometry={nodes.Cube001.geometry} material={materials['Default OBJ']}/>
            </group>
        </mesh>
    )
}

useGLTF.preload('/models/Earth.glb')
