/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef} from 'react'
import * as THREE from "three";
import {useGLTF} from '@react-three/drei'

export const SUN_SIZE = 0.015;

export default function Sun(props) {
    const group = useRef();
    const gltf = useGLTF('/models/Sun.glb');

    return (
        <>
            {/*<primitive ref={props.sunRef} {...props} scale={SUN_SIZE} object={gltf.scene} emissiveIntensity={0.1} emissive={new THREE.Color(0xFFFFFF)}>*/}
                <pointLight {...props} intensity={1.5} />
            {/*</primitive>*/}
        </>
    )
}

useGLTF.preload('/models/Sun.glb')
